### ISSUE TITLE
运行环境都满足，但是一运行就闪退

### ISSUE THREAD

**Issue by EliasMercer** [Elaina-Alex/HedgehogCatAppNovelDownload#1]
https://user-images.githubusercontent.com/90075518/170869398-0701a1c8-c8f4-452a-abad-724e1d5be836.mp4

hang333大佬的代码我这儿倒是可以运行

**Comment by Elaina-Alex** [comment]
十分感谢你的反馈，项目并不是直接点击run.py运行的，请在项目文件夹内打开终端，输入python run.py打开交互界面，也可以直接使用命令python run.py 加上指令来操作，如果还有不懂的地方，我乐意可以提供帮助给你

**Comment by EliasMercer** [comment]
> 十分感谢你的反馈，项目并不是直接点击项目文件下的 run.py 文件运行的，而且一般而言python的源代码也不会是如此直接点击运行，而是通过python 或者 py命令运行。 请在项目文件夹内打开终端，输入python run.py 打开交互界面，也可以直接使用命令python run.py 加上指令来操作，如果还有不懂的地方，我乐意可以为您提供帮助给你

![屏幕截图 2022-05-30 102250](https://user-images.githubusercontent.com/90075518/170905939-d40e2e3b-bee0-411b-802c-f2fbe5187bf4.png)
是这样操作吗？

**Comment by Elaina-Alex** [comment]
> 

是的，你的运行方法没有问题，不过你缺少ebooklib模块，请尝试使用pip install ebooklib模块安装，如果无法安装，请删除项目目录下的Epub.py文件，这个文件和下载epub电子书格式文件有关，不过现在还没有完善，删去这个文件不会影响运行

**Comment by Elaina-Alex** [comment]
如果问题解决了，我将关闭这个issues。

**Comment by EliasMercer** [comment]
> > 
> 
> 是的，你的运行方法没有问题，不过你缺少ebooklib模块，请尝试使用pip install ebooklib模块安装，如果无法安装，请删除项目目录下的 Epub.py 文件，并且删去 book.py 文件第一行 import Epub 这个文件和下载epub电子书格式文件有关，不过现在还没有完善，删去这个文件不会影使用。

这个我刚去csdn查了解决方法，已经解决了，把那些缺少的模块一安装，直接点run.py文件就可以运行了

**Comment by EliasMercer** [comment]
> 如果问题解决了，我将关闭这个issues。

还没完全好，麻烦等等。密码我刚改的但是就是登录不上
![B$VQH8V}EKKON7%U{TFIE{N_edit_184370830023429](https://user-images.githubusercontent.com/90075518/170908180-47cbe27c-93d2-4157-936d-0fd3715a2190.png)

**Comment by Elaina-Alex** [comment]
login 账号 密码
不用输入<>

**Comment by EliasMercer** [comment]
> login 账号 密码 不用输入<>

已经好了，麻烦大佬了，删吧
