### ISSUE TITLE
用不了了，账号一直登陆不上

### ISSUE THREAD

**Issue by shiki-su** [Elaina-Alex/HedgehogCatAppNovelDownload#3]
最近刺猬猫下架的书有些多，希望能尽快改好

**Comment by Elaina-Alex** [comment]
关于这个问题，刺猬猫数据库似乎出了一些，在大部分时间段哪怕是正确的账号密码都会显示密码错误，在APP登入同样如此，可以改密码解决。

**Comment by shiki-su** [comment]
试了，但是没用

**Comment by Elaina-Alex** [comment]
> 试了，但是没用

有时间我看看。

**Comment by shiki-su** [comment]
> > 试了，但是没用
> 
> 有时间我看看。

好的，麻烦了

**Comment by Elaina-Alex** [comment]
> > > 试了，但是没用
> > 
> > 
> > 有时间我看看。
> 
> 好的，麻烦了

已经确定刺猬猫在登录上添加了极客的滑块验证，你可以使用token绕过这个验证绕过这个验证

**Comment by shiki-su** [comment]
> > > > 试了，但是没用
> > > 
> > > 
> > > 有时间我看看。
> > 
> > 
> > 好的，麻烦了
> 
> 已经确定刺猬猫在登录上添加了极客的滑块验证，你可以使用token绕过这个验证绕过这个验证

请问具体怎么操作

**Comment by Elaina-Alex** [comment]
废弃账号登入，转为使用login_token and account   进行登入
